In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\LENOVO\Downloads\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [7]:
base_flavor = df.groupby('Base Flavor')
base_flavor.mean(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [10]:
base_flavor = df.groupby('Base Flavor').mean(numeric_only = True)
base_flavor

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [11]:
base_flavor = df.groupby('Base Flavor').count()
base_flavor

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [12]:
base_flavor = df.groupby('Base Flavor').min()
base_flavor

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [13]:
base_flavor = df.groupby('Base Flavor').max()
base_flavor

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [20]:
base_flavor = df.groupby('Base Flavor').agg({'Flavor Rating' : ['min', 'max', 'count', 'sum'], 'Texture Rating' : ['min','max','count','sum']})
base_flavor

            Flavor Rating                   Texture Rating
                      min   max count   sum            min  max count   sum
Base Flavor
Chocolate             8.2   8.8     3  25.2            7.0  7.6     3  21.7
Vanilla               2.3  10.0     6  34.2            3.4  8.0     6  33.9

In [21]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [25]:
df.groupby(['Base Flavor','Liked']).mean(numeric_only = True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [26]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating' : ['min','max','count','sum']})

                  Flavor Rating
                            min   max count   sum
Base Flavor Liked
Chocolate   Yes             8.2   8.8     3  25.2
Vanilla     No              2.3   4.7     3  10.8
            Yes             6.5  10.0     3  23.4

In [27]:
df.groupby('Flavor').describe()

                       Flavor Rating                                          \
                               count  mean std   min   25%   50%   75%   max
Flavor
Cake Batter                      1.0   6.5 NaN   6.5   6.5   6.5   6.5   6.5
Chocolate                        1.0   8.8 NaN   8.8   8.8   8.8   8.8   8.8
Chocolte Fudge Brownie           1.0   8.2 NaN   8.2   8.2   8.2   8.2   8.2
Cookie Dough                     1.0   6.9 NaN   6.9   6.9   6.9   6.9   6.9
Mint Chocolate Chip              1.0  10.0 NaN  10.0  10.0  10.0  10.0  10.0
Neapolitan                       1.0   3.8 NaN   3.8   3.8   3.8   3.8   3.8
Pistachio                        1.0   2.3 NaN   2.3   2.3   2.3   2.3   2.3
Rocky Road                       1.0   8.2 NaN   8.2   8.2   8.2   8.2   8.2
Vanilla                          1.0   4.7 NaN   4.7   4.7   4.7   4.7   4.7

                       Texture Rating       ...           Total Rating        \
                                count mean  ...  75%  max        count  mean
Flavor                                      ...
Cake Batter                       1.0  6.0  ...  6.0  6.0          1.0  12.5
Chocolate                         1.0  7.6  ...  7.6  7.6          1.0  16.6
Chocolte Fudge Brownie            1.0  7.1  ...  7.1  7.1          1.0  15.3
Cookie Dough                      1.0  6.5  ...  6.5  6.5          1.0  13.4
Mint Chocolate Chip               1.0  8.0  ...  8.0  8.0          1.0  18.0
Neapolitan                        1.0  5.0  ...  5.0  5.0          1.0   8.8
Pistachio                         1.0  3.4  ...  3.4  3.4          1.0   5.7
Rocky Road                        1.0  7.0  ...  7.0  7.0          1.0  15.2
Vanilla                           1.0  5.0  ...  5.0  5.0          1.0   9.7


                       std   min   25%   50%   75%   max
Flavor
Cake Batter            NaN  12.5  12.5  12.5  12.5  12.5
Chocolate              NaN  16.6  16.6  16.6  16.6  16.6
Chocolte Fudge Brownie NaN  15.3  15.3  15.3  15.3  15.3
Cookie Dough           NaN  13.4  13.4  13.4  13.4  13.4
Mint Chocolate Chip    NaN  18.0  18.0  18.0  18.0  18.0
Neapolitan             NaN   8.8   8.8   8.8   8.8   8.8
Pistachio              NaN   5.7   5.7   5.7   5.7   5.7
Rocky Road             NaN  15.2  15.2  15.2  15.2  15.2
Vanilla                NaN   9.7   9.7   9.7   9.7   9.7

[9 rows x 24 columns]

In [36]:
df.groupby('Base Flavor').describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [30]:
df.groupby('Flavor').mean(numeric_only = True)

                        Flavor Rating  Texture Rating  Total Rating
Flavor
Cake Batter                       6.5             6.0          12.5
Chocolate                         8.8             7.6          16.6
Chocolte Fudge Brownie            8.2             7.1          15.3
Cookie Dough                      6.9             6.5          13.4
Mint Chocolate Chip              10.0             8.0          18.0
Neapolitan                        3.8             5.0           8.8
Pistachio                         2.3             3.4           5.7
Rocky Road                        8.2             7.0          15.2
Vanilla                           4.7             5.0           9.7